package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.ToggleGroup;
import javafx.stage.Stage;

import java.net.URL;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;
import javafx.scene.control.RadioButton;
import javafx.scene.control.ChoiceBox;

public class AddStudentDialogController implements Initializable {
	@FXML
	private Button btnSubmit;
	@FXML
	private Button btnCancel;
	@FXML
	private CheckBox isHonors;
	@FXML
	private DatePicker dateOfBirth;
	@FXML
	private ComboBox comboGrade;
	@FXML
	private TextField tfNameEnglish;
	@FXML
	private TextField tfNameKorean;
	@FXML
	private CheckBox isDorm;
	@FXML
	private ChoiceBox choiceCampus;
	@FXML
	private DatePicker dateEnrollment;
	
	@FXML
    private ToggleGroup gender;
    @FXML
    private RadioButton radioFemale;

    @FXML
    private RadioButton radioMale;

	// Event Listener on Button[#btnSubmit].onAction
	@FXML
	public void submitAction(ActionEvent event) throws SQLException {
		
		String nameEnglish=tfNameEnglish.getText();
		String nameKorean=tfNameKorean.getText();
		String grade=comboGrade.getSelectionModel().getSelectedItem().toString();
		boolean dorm=isDorm.isSelected();
		boolean honors=isHonors.isSelected();
		String gender=radioMale.isSelected() ? "Male" : "Female";
		String doB=dateOfBirth.getValue().toString();
		LocalDate enroll=dateEnrollment.getValue();
		String campus=(String) choiceCampus.getValue();
		
		
		System.out.println(nameEnglish);
		System.out.println(nameKorean);
		System.out.println(grade);
		System.out.println(dorm);
		System.out.println(honors);
		System.out.println(doB);
		System.out.println(enroll);
		System.out.println(campus);
		//public Student(int grade, String nameEnglish, String nameKorean, String campus, String gender, String doB, boolean isHonors, boolean isLivingDorm) {

	
		Student student=new Student(Integer.valueOf(grade), nameEnglish, nameKorean, campus, gender, doB, honors, dorm);
	
		
		Data.addStudent(student);
		Data.students.add(student);
		Stage stage = (Stage) btnSubmit.getScene().getWindow();
		stage.close();
	}
	
	@FXML
    void nameEnglishAction(ActionEvent event) {
		
    }
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void cancelAction(ActionEvent event) {
		Stage stage = (Stage) btnCancel.getScene().getWindow();
		stage.close();
	}
	// Event Listener on CheckBox[#isHonors].onAction
	@FXML
	public void isHonorsAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#dateOfBirth].onAction
	@FXML
	public void doBAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#comboGrade].onAction
	@FXML
	public void gradeAction(ActionEvent event) {
		//String data=comboGrade.getSelectionModel().getSelectedItem().toString();
		
	}
	// Event Listener on CheckBox[#isDorm].onAction
	@FXML
	public void isDormAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#dateEnrollment].onAction
	@FXML
	public void enrollmentAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
    void genderAction(ActionEvent event) {

    }
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		String[] grades= {"Kindergarten", "1", "2", "3", "4", "5" , "6" ,"7" ,"8", "9", "10", "11", "12"};
		comboGrade.getItems().addAll(grades);
		choiceCampus.getItems().addAll("Incheon", "Seochoe", "Bellville");
		
		
	}
}
