package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.ResourceBundle;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.ComboBox;

import javafx.scene.control.Spinner;
import javafx.scene.control.SpinnerValueFactory;
import javafx.scene.control.ChoiceBox;

public class AddSubjectDialogController implements Initializable {
	@FXML
	private TextField newSubjectName;
	@FXML
	private Spinner<Integer> spinnerCredits;
	@FXML
	private Button btnSubmit;
	@FXML
	private Button btnCancel;
	
	@FXML private Button btnSubjectAddGrades;
	@FXML private Button btnSubjectRemoveGrades;
	
	@FXML
	private ComboBox comboTeachers;
	@FXML
	private ChoiceBox<Integer> newSubjectYear;
	@FXML
	private ChoiceBox<String> newSubjectSemester;
	@FXML
	private ListView newSubjectGradesAll;
	@FXML
	private ListView newSubjectGrades;
	@FXML
	private ComboBox comboCampus;
	
	ArrayList<Teacher> teachersList=new ArrayList<Teacher>();
	SpinnerValueFactory<Integer> valueFactory;

	// Event Listener on TextField[#newSubjectName].onAction
	@FXML
	public void newSubjectNameAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSubmit].onAction
	@FXML
	public void submitAction(ActionEvent event) throws SQLException {
		String campus=comboCampus.getSelectionModel().getSelectedItem().toString();
		Integer year=newSubjectYear.getValue();
		String semester=newSubjectSemester.getValue();
		String subjectName=newSubjectName.getText();
		String teacher=comboTeachers.getSelectionModel().getSelectedItem().toString();
		System.out.println(teacher);
		Integer credits=spinnerCredits.getValue();
		String gradelist="";
		for(int i=0;i<newSubjectGrades.getItems().size();i++) {
			if(i<newSubjectGrades.getItems().size()-1)
				gradelist+=newSubjectGrades.getItems().get(i)+",";
			else
				gradelist+=newSubjectGrades.getItems().get(i);
		}
	
		
		Subject subject=new Subject(campus, year, semester, subjectName, credits, teacher, gradelist);
	
		
		Data.addSubject(subject);
		Data.subjects.add(subject);
		Stage stage = (Stage) btnSubmit.getScene().getWindow();
		stage.close();
	}
	
	@FXML
	public void addGradesAction(ActionEvent event) {
		int selectedIndex=newSubjectGradesAll.getSelectionModel().getSelectedIndex();
		if(selectedIndex>-1) {
			//System.out.println(listSubjects.getItems());
			newSubjectGrades.getItems().add(newSubjectGradesAll.getItems().get(selectedIndex));
			newSubjectGradesAll.getItems().remove(selectedIndex);
			//System.out.println(listSubjects.getItems());
			System.out.println(newSubjectGrades.getItems());
			//System.out.println(selectedIndex);
			selectedIndex=-1;
			//System.out.println(selectedIndex);
			newSubjectGradesAll.getSelectionModel().clearSelection();
		}
		
		
		
		
	}
	// Event Listener on Button[#removeTeaching].onAction
	@FXML
	public void removeGradesAction(ActionEvent event) {
		int selectedIndex=newSubjectGrades.getSelectionModel().getSelectedIndex();
		if(selectedIndex>-1) {
			System.out.println(newSubjectGrades.getItems());
			newSubjectGradesAll.getItems().add(newSubjectGrades.getItems().get(selectedIndex));
			newSubjectGrades.getItems().remove(selectedIndex);
			selectedIndex=-1;
			newSubjectGrades.getSelectionModel().clearSelection();
		}
	}
	
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void cancelAction(ActionEvent event) {
		Stage stage = (Stage) btnCancel.getScene().getWindow();
		stage.close();
	}
	// Event Listener on ComboBox[#comboCampus].onAction
	@FXML
	public void comboCampusAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public ArrayList<String> teacherNames(){
		ArrayList<String> teacherStringList=new ArrayList<String>();
		ObservableList<Teacher> teacherlist=Data.getAllTeachers();
		for(Teacher t: teacherlist) {
			teacherStringList.add(t.getName());
		}
		
		return teacherStringList;
		
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		valueFactory=new SpinnerValueFactory.IntegerSpinnerValueFactory(1, 6);
		spinnerCredits.setValueFactory(valueFactory);
		comboTeachers.getItems().addAll(Data.teacherNames);
		newSubjectGradesAll.getItems().addAll(12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1);
		comboCampus.getItems().addAll("Incheon", "Seocho", "Belleville");
		newSubjectYear.getItems().addAll(2024, 2025);
		newSubjectSemester.getItems().addAll("Semester 1", "Semester 2", "Winter Camp", "Summer Camp");
		
	}
}
