package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.net.URL;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.ResourceBundle;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.ComboBox;

import javafx.scene.control.Spinner;
import javafx.scene.control.SpinnerValueFactory;
import javafx.scene.control.ChoiceBox;

public class EditSubjectDialogController implements Initializable {
	@FXML
	private TextField newSubjectName;
	@FXML
	private Spinner<Integer> spinnerCredits;
	@FXML
	private Button btnApplyChanges;
	@FXML
	private Button btnCancel;
	@FXML
	private ComboBox comboTeachers;
	@FXML
	private ChoiceBox<Integer> newSubjectYear;
	@FXML
	private ChoiceBox<String> newSubjectSemester;
	@FXML
	private ListView newSubjectGradesAll;
	@FXML
	private ListView newSubjectGrades;
	@FXML
	private Button btnSubjectAddGrades;
	@FXML
	private Button btnSubjectsRemoveGrades;
	@FXML
	private ComboBox comboCampus;
	
	private String id;
	
	ArrayList<Teacher> teachersList=new ArrayList<Teacher>();
	SpinnerValueFactory<Integer> valueFactory;

	public void loadData(Subject subject) {
		
		id=subject.getId();
		comboCampus.setValue(subject.getCampus().getCampus());
		newSubjectName.setText(subject.getName());
		newSubjectYear.setValue(subject.getYear());
		newSubjectSemester.setValue(subject.getSemester());
		comboTeachers.setValue(subject.getTeacherName());
		spinnerCredits.getValueFactory().setValue(subject.getCredits());
		
		String[] gl=subject.getGradesList().split(",");
		for(int i=0;i<gl.length;i++) {
			newSubjectGrades.getItems().add(Integer.valueOf(gl[i]));
		}
		
//		System.out.println(newSubjectGrades.getItems().size());
//		for(Object j: newSubjectGrades.getItems()) {
//			System.out.println(j);
//		}
		
		for(int i=0;i<newSubjectGradesAll.getItems().size();i++) {
			for(int j=0;j<gl.length;j++) {
				System.out.println(newSubjectGradesAll.getItems().get(i)+" ");
				if(newSubjectGradesAll.getItems().get(i)==Integer.valueOf(gl[j])) {
					System.out.println(newSubjectGradesAll.getItems().get(i)+" "+gl[j]);
					newSubjectGradesAll.getItems().remove(i);
					i--;
				}
			}
		}
		
			
	}

	@FXML
	public void newSubjectNameAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnApplyChanges].onAction
	@FXML
	public void applyChangesAction(ActionEvent event) throws SQLException {
		
		String campus=comboCampus.getSelectionModel().getSelectedItem().toString();
		Integer year=newSubjectYear.getValue();
		String semester=newSubjectSemester.getValue();
		String subjectName=newSubjectName.getText();
		String teacher=comboTeachers.getSelectionModel().getSelectedItem().toString();
		System.out.println(teacher);
		Integer credits=spinnerCredits.getValue();
		String gradelist="";
		for(int i=0;i<newSubjectGrades.getItems().size();i++) {
			if(i<newSubjectGrades.getItems().size()-1)
				gradelist+=newSubjectGrades.getItems().get(i)+",";
			else
				gradelist+=newSubjectGrades.getItems().get(i);
		}
	
		
		Subject subject=new Subject(id, campus, year, semester, subjectName, credits, teacher, gradelist);
	
		
		Data.updateSubject(subject);
		
		for(int i=0;i<Data.subjects.size();i++) {
			if(Data.subjects.get(i).getId()==id) {
				
				Data.subjects.get(i).setCampus(new School(campus));
				Data.subjects.get(i).setCampusName(campus);
				Data.subjects.get(i).setYear(year);
				Data.subjects.get(i).setSemester(semester);
				Data.subjects.get(i).setTeacherName(teacher);
				Data.subjects.get(i).setCredits(credits);
				Data.subjects.get(i).setGradesList(gradelist);
				Data.subjects.get(i).setName(subjectName);
			}
		}
		
		
		Stage stage = (Stage) btnApplyChanges.getScene().getWindow();
		stage.close();
	}
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void cancelAction(ActionEvent event) {
		Stage stage = (Stage) btnCancel.getScene().getWindow();
		stage.close();
	}
	// Event Listener on Button[#btnSubjectAddGrades].onAction
	@FXML
	public void addGradesAction(ActionEvent event) {
		int selectedIndex=newSubjectGradesAll.getSelectionModel().getSelectedIndex();
		if(selectedIndex>-1) {
			//System.out.println(listSubjects.getItems());
			newSubjectGrades.getItems().add(newSubjectGradesAll.getItems().get(selectedIndex));
			newSubjectGradesAll.getItems().remove(selectedIndex);
			//System.out.println(listSubjects.getItems());
			//System.out.println(newSubjectGrades.getItems());
			//System.out.println(selectedIndex);
			selectedIndex=-1;
			//System.out.println(selectedIndex);
			newSubjectGradesAll.getSelectionModel().clearSelection();
		}
		
		
		
		
	}
	// Event Listener on Button[#removeTeaching].onAction
	@FXML
	public void removeGradesAction(ActionEvent event) {
		int selectedIndex=newSubjectGrades.getSelectionModel().getSelectedIndex();
		if(selectedIndex>-1) {
			//System.out.println(newSubjectGrades.getItems());
			newSubjectGradesAll.getItems().add(newSubjectGrades.getItems().get(selectedIndex));
			newSubjectGrades.getItems().remove(selectedIndex);
			selectedIndex=-1;
			newSubjectGrades.getSelectionModel().clearSelection();
		}
	}
	// Event Listener on ComboBox[#comboCampus].onAction
	@FXML
	public void comboCampusAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public ArrayList<String> teacherNames(){
		ArrayList<String> teacherStringList=new ArrayList<String>();
		ObservableList<Teacher> teacherlist=Data.getAllTeachers();
		for(Teacher t: teacherlist) {
			teacherStringList.add(t.getName());
		}
		
		return teacherStringList;
		
	}

	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		valueFactory=new SpinnerValueFactory.IntegerSpinnerValueFactory(1, 6);
		spinnerCredits.setValueFactory(valueFactory);
		comboTeachers.getItems().addAll(teacherNames());
		newSubjectGradesAll.getItems().addAll(12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1);
		comboCampus.getItems().addAll("Incheon", "Seocho", "Belleville");
		newSubjectYear.getItems().addAll(2024, 2025);
		newSubjectSemester.getItems().addAll("Semester 1", "Semester 2", "Winter Camp", "Summer Camp");
		
	}
}
