package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;
import javafx.stage.Stage;

import java.net.URL;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.RadioButton;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.ChoiceBox;

public class EditStudentDialogController implements Initializable {
	@FXML
	private CheckBox isHonors;
	@FXML
	private DatePicker dateOfBirth;
	@FXML
	private ComboBox comboGrade;
	@FXML
	private TextField tfNameEnglish;
	@FXML
	private TextField tfNameKorean;
	@FXML
	private CheckBox isDorm;
	@FXML
	private ChoiceBox choiceCampus;
	@FXML
	private DatePicker dateEnrollment;
	@FXML
	private Button btnApplyChanges;
	@FXML
	private Button btnCancel;
	@FXML
	private RadioButton radioMale;
	@FXML
	private ToggleGroup gender;
	@FXML
	private RadioButton radioFemale;
	
	private String id;
	
	public void loadData(Student student) {
		
		id=student.getId();
		if(student.getHonors().equals("true")) {
			isHonors.setSelected(true);
		} else {
			isHonors.setSelected(false);
		}
		
		if(student.isLivingDorm()==true) {
			isDorm.setSelected(true);
		} else {
			isDorm.setSelected(false);
		}
		
		comboGrade.setValue(student.getGrade());
		
		choiceCampus.setValue(student.getCampus().getCampus());
		
		tfNameEnglish.setText(student.getNameEnglish());
		tfNameKorean.setText(student.getNameKorean());
		
		String[] dob=student.getDoB().split("-");
		LocalDate date=LocalDate.of(Integer.valueOf(dob[0]), Integer.valueOf(dob[1]), Integer.valueOf(dob[2]));
		dateOfBirth.setValue(date);
		
		String[] enrollment=student.getEnrollmentDate().split("-");
		LocalDate date2=LocalDate.of(Integer.valueOf(enrollment[0]), Integer.valueOf(enrollment[1]), Integer.valueOf(enrollment[2]));
		dateEnrollment.setValue(date2);
		
		
					
	}

	// Event Listener on CheckBox[#isHonors].onAction
	@FXML
	public void isHonorsAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#dateOfBirth].onAction
	@FXML
	public void doBAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#comboGrade].onAction
	@FXML
	public void gradeAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfNameEnglish].onAction
	@FXML
	public void nameEnglishAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#isDorm].onAction
	@FXML
	public void isDormAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#dateEnrollment].onAction
	@FXML
	public void enrollmentAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnApplyChanges].onAction
	@FXML
	public void applyChangesAction(ActionEvent event) throws SQLException {
		
		String nameEnglish=tfNameEnglish.getText();
		String nameKorean=tfNameKorean.getText();
		String grade=comboGrade.getSelectionModel().getSelectedItem().toString();
		String dorm=isDorm.isSelected() ? "Yes" : "No";
		String honors=isHonors.isSelected() ? "Yes" : "No";
		String gender=radioMale.isSelected() ? "Male" : "Female";
		String doB=dateOfBirth.getValue().toString();
		String enroll=dateEnrollment.getValue().toString();
		String campus=(String) choiceCampus.getValue();
		
		
//		System.out.println(nameEnglish);
//		System.out.println(nameKorean);
//		System.out.println(grade);
//		System.out.println(dorm);
//		System.out.println(honors);
		System.out.println(doB);
		System.out.println(enroll);
//		System.out.println(campus);
		//public Student(int grade, String nameEnglish, String nameKorean, String campus, String gender, String doB, boolean isHonors, boolean isLivingDorm) {

	
		Student student=new Student(id, Integer.valueOf(grade), nameEnglish, nameKorean, campus, gender, doB, enroll, isHonors.isSelected(), isDorm.isSelected());
			
		Data.updateStudent(student);
		
		
		for(int i=0;i<Data.subjects.size();i++) {
			if(Data.students.get(i).getId()==id) {
				
				Data.students.get(i).setCampus(new School(campus));
				Data.students.get(i).setCampusName(campus);
				Data.students.get(i).setNameEnglish(nameEnglish);
				Data.students.get(i).setNameKorean(nameKorean);
				Data.students.get(i).setGender(gender);
				Data.students.get(i).setDoB(doB);
				Data.students.get(i).setDorm(dorm);
				Data.students.get(i).setHonors(honors);
				Data.students.get(i).setEnrollmentDate(enroll);
			}
		}
		
		
		Stage stage = (Stage) btnApplyChanges.getScene().getWindow();
		stage.close();
	}
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void cancelAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#radioMale].onAction
	@FXML
	public void genderAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#radioFemale].onAction
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		String[] grades= {"Kindergarten", "1", "2", "3", "4", "5" , "6" ,"7" ,"8", "9", "10", "11", "12"};
		comboGrade.getItems().addAll(grades);
		choiceCampus.getItems().addAll("Incheon", "Seochoe", "Bellville");
		
	}
	
}
