package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import javafx.scene.control.Dialog;
import javafx.scene.control.DialogPane;
import javafx.scene.layout.Pane;

public class ScheduleMatrixController implements Initializable {
	@FXML
	private ComboBox comboYear;
	@FXML
	private ComboBox comboSemester;
	@FXML
	private ComboBox comboSchool;
	@FXML
	private ComboBox comboCampus;
	@FXML
	private ComboBox comboTeacher;
	@FXML
	private Button period1;
	@FXML
	private Button period2;
	@FXML
	private Button period3;
	@FXML
	private Button period4;
	@FXML
	private Button lunch;
	@FXML
	private Button period6;
	@FXML
	private Button period7;
	@FXML
	private Button period8;
	@FXML
	private Button p11;
	@FXML
	private Button p12;
	@FXML
	private Button p13;
	@FXML
	private Button p14;
	@FXML
	private Button p15;
	@FXML
	private Button p16;
	@FXML
	private Button p17;
	@FXML
	private Button p18;
	@FXML
	private Button p21;
	@FXML
	private Button p22;
	@FXML
	private Button p23;
	@FXML
	private Button p24;
	@FXML
	private Button p25;
	@FXML
	private Button p26;
	@FXML
	private Button p27;
	@FXML
	private Button p28;
	@FXML
	private Button p31;
	@FXML
	private Button p32;
	@FXML
	private Button p33;
	@FXML
	private Button p34;
	@FXML
	private Button p35;
	@FXML
	private Button p36;
	@FXML
	private Button p37;
	@FXML
	private Button p38;
	@FXML
	private Button p41;
	@FXML
	private Button p42;
	@FXML
	private Button p43;
	@FXML
	private Button p44;
	@FXML
	private Button p45;
	@FXML
	private Button p46;
	@FXML
	private Button p47;
	@FXML
	private Button p48;
	@FXML
	private Button p51;
	@FXML
	private Button p52;
	@FXML
	private Button p53;
	@FXML
	private Button p54;
	@FXML
	private Button p55;
	@FXML
	private Button p56;
	@FXML
	private Button p57;
	@FXML
	private Button p58;

	// Event Listener on ComboBox[#comboYear].onAction
	@FXML
	public void yearAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#comboSemester].onAction
	@FXML
	public void semesterAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#comboSchool].onAction
	@FXML
	public void schoolAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#comboCampus].onAction
	@FXML
	public void campusAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#comboTeacher].onAction
	@FXML
	public void teacherAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#period1].onAction
	@FXML
	public void period1Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#period2].onAction
	@FXML
	public void period2Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#period3].onAction
	@FXML
	public void period3Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#period4].onAction
	@FXML
	public void period4Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#lunch].onAction
	@FXML
	public void lunchAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#period6].onAction
	@FXML
	public void period6Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#period7].onAction
	@FXML
	public void period7Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#period8].onAction
	@FXML
	public void period8Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p11].onAction
	@FXML
	public void p11Action(ActionEvent event) throws IOException {
		FXMLLoader fxmlLoader=new FXMLLoader(Main.class.getResource("PeriodDialog.fxml"));
		//fxmlLoader.setLocation(getClass().getResource("PeriodDialog.fxml"));
		DialogPane periodDialog=fxmlLoader.load();
		
		PeriodDialogController periodDialogController=fxmlLoader.getController();
		periodDialogController.loadData(1, 1);
		
//		Dialog<ButtonType> dialog=new Dialog<>();
//		dialog.setDialogPane(periodDialog);
//		dialog.setTitle("Day 1 period 1");
	}
	// Event Listener on Button[#p12].onAction
	@FXML
	public void p12Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p13].onAction
	@FXML
	public void p13Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p14].onAction
	@FXML
	public void p14Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p15].onAction
	@FXML
	public void p15Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p16].onAction
	@FXML
	public void p16Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p17].onAction
	@FXML
	public void p17Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p18].onAction
	@FXML
	public void p18Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p21].onAction
	@FXML
	public void p21Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p22].onAction
	@FXML
	public void p22Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p23].onAction
	@FXML
	public void p23Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p24].onAction
	@FXML
	public void p24Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p25].onAction
	@FXML
	public void p25Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p26].onAction
	@FXML
	public void p26Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p27].onAction
	@FXML
	public void p27Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p28].onAction
	@FXML
	public void p28Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p31].onAction
	@FXML
	public void p31Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p32].onAction
	@FXML
	public void p32Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p33].onAction
	@FXML
	public void p33Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p34].onAction
	@FXML
	public void p34Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p35].onAction
	@FXML
	public void p35Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p36].onAction
	@FXML
	public void Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p37].onAction
	@FXML
	public void p37Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p38].onAction
	@FXML
	public void p38Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p41].onAction
	@FXML
	public void p41Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p42].onAction
	@FXML
	public void p42Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p43].onAction
	@FXML
	public void p43Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p44].onAction
	@FXML
	public void p44Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p45].onAction
	@FXML
	public void p45Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p46].onAction
	@FXML
	public void p46Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p47].onAction
	@FXML
	public void p47Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p48].onAction
	@FXML
	public void p48Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p51].onAction
	@FXML
	public void p51Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p52].onAction
	@FXML
	public void p52Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p53].onAction
	@FXML
	public void p53Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p54].onAction
	@FXML
	public void p54Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p55].onAction
	@FXML
	public void p55Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p56].onAction
	@FXML
	public void p56Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p57].onAction
	@FXML
	public void p57Action(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#p58].onAction
	@FXML
	public void p58Action(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
