package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.ChoiceBox;

public class GiveBlessingPageController {
	@FXML
	private TextArea taReason;
	@FXML
	private ComboBox cbNumber;
	@FXML
	private DatePicker datePicker;
	@FXML
	private Button btnSubmit;
	@FXML
	private CheckBox chParent;
	@FXML
	private Label receivingStudent;
	@FXML
	private ChoiceBox choiceReason;
	@FXML
	private Button btnCancel;

	// Event Listener on TextArea[#taReason].onDragDetected
	@FXML
	public void reasonAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cbNumber].onAction
	@FXML
	public void numberAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on DatePicker[#datePicker].onAction
	@FXML
	public void dateAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSubmit].onAction
	@FXML
	public void submitAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#chParent].onAction
	@FXML
	public void parentAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void cancelAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
